name: Deploy Deja Vu to Chrome Web Store

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Zip Chrome Extension
        run: zip -r deja-vu.zip .

      - name: Upload to Chrome Web Store
        uses: wdzeng/chrome-extension-upload-action@v2
        with:
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          zip-file: "deja-vu.zip"
